---

# run on all hosts defined in inventory file
- hosts: all

  # become root
  become: true

  # installing pre-reqs for Python & installing Python
  tasks:
    - name: Install pre-requisites
      apt:
        name: software-properties-common              # installing supporting software
        state: present

    - name: Add deadsnakes repo to sources list       # updating apt repo with deadsnakes
      apt_repository: repo="ppa:deadsnakes/ppa"

    - name: Install Python
      apt: 
        name: python3.8                               # installing Python 3.8
        state: present
